# This is a basic workflow to help you get started with Actions

name: CI
env:
  AWS_DEFAULT_REGION: eu-west-1
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ main, cypress_test ]
    paths-ignore: 
      - 'sow-rest-*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-ami:
    runs-on: ubuntu-latest
    steps:
      - name: Get the current instance id
        id: get_id
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
        run: |
          # instance_id="${{ steps.deploy.outputs.instance_id }}"
          instance_id=$(aws ec2 describe-instances --filters 'Name=tag:Name,Values=dev-k8-rebuild' --output text --query 'Reservations[*].Instances[*].InstanceId')
          echo ::set-output name=instance_id::$instance_id
      
      - name: Checkout submodules
        uses: actions/checkout@v2
        with:
          repository: MariuszFerdyn/vmware-scripts
          path: vmware-scripts

      - name: Run tests on the VM
        run: |
          #!/bin/bash
          # echo "Add api tests here for ${{ steps.deploy.outputs.instance_id }}"
          # instance_ip="${{ steps.deploy.outputs.instance_ip }}"
          instance_ip="54.75.57.181"
          cd vmware-scripts/HealthFunctionalTests/filedrop
          npm ci
          sed -i "s/3.133.161.191/$instance_ip/g" cypress/integration/filedrop.spec.js
          npm test
          test_status=$?
          echo "test_status is $test_status"
